
default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info


stages:
  - build
  - deploy

build_job:
  stage: build
  script: |
    echo "Building the application > > >"
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    docker build -t "$DOCKER_IMAGE_NAME:$CI_COMMIT_SHA .
    docker push "$DOCKER_IMAGE_NAME:$CI_COMMIT_SHA

deploy_job:
  stage: deploy
  script: |
    echo "pulling the image now > > >"
    docker pull "$DOCKER_IMAGE_NAME:$CI_COMMIT_SHA
    docker rm -f swagger-ec2-container
    docker run -d -p 5000:5000 --name swagger-ec2-container "$DOCKER_IMAGE_NAME:$CI_COMMIT_SHA

  tags:
    - ec2-runner
  only:
    - main     